{
 "title": "Ghost server performance",
 "tags": [
  "docker",
  "app"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"ghost_server\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU Usage for Ghost server container",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "% CPU used" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"ghost_server\"}[1m]) * 100"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"ghost_server\"}[1m])"
    },
    {
     "expr": "rate(container_network_receive_packets_dropped_total{name=\"ghost_server\"}[1m])"
    }
   ]
  }
 ]
}